version: '3.5'
services:
  web:
    build: .
    command: node server.js
    volumes:
      - .:/usr/dockerRs/
      - /usr/dockerRs/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongors1n1
      - mongors1n2
      - mongors1n3
      - mongors2n1
      - mongors2n2
      - mongors2n3
      - mongocfg1
      - mongocfg2
      - mongocfg3
      - mongos1
      - mongos2
  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --port 27017
    ports:
      - "27017:27017"
    expose:
      - "27017"
  mongors1n2:
    container_name: mongors1n2
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --port 27017
    ports:
      - "27027:27017"
    expose:
      - "27017"
  mongors1n3:
    container_name: mongors1n3
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --port 27017
    ports:
      - "27037:27017"
    expose:
      - "27017"

  mongors2n1:
    container_name: mongors2n1
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --port 27017
    ports:
      - "27047:27017"
    expose:
      - "27017"
  mongors2n2:
    container_name: mongors2n2
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --port 27017
    ports:
      - "27057:27017"
    expose:
      - "27017"
  mongors2n3:
    container_name: mongors2n3
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --port 27017
    ports:
      - "27067:27017"
    expose:
      - "27017"

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    expose:
      - "27017"
  mongocfg2:
    container_name: mongocfg2
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    expose:
      - "27017"
  mongocfg3:
    container_name: mongocfg3
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --port 27017
    expose:
      - "27017"

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27019
    ports:
      - "27019:27017"
    expose:
      - "27017"
      - "27018"
      - "27019"
  mongos2:
    container_name: mongos2
    image: mongo
    depends_on:
      - mongocfg1
      - mongocfg2
      - mongocfg3
    command: mongos --configdb mongors1conf/mongocfg1:27017,mongocfg2:27017,mongocfg3:27017 --port 27019
    ports:
      - "27020:27017"
    expose:
      - "27017"
      - "27018"
      - "27019"

